# Generated by Django 4.2 on 2026-04-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Bautismo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Comunion',
            field=models.BooleanField(default=True),
        ),
    ]
