# Generated by Django 4.2 on 2026-04-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_persona_bautismo_alter_persona_comunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacabecera',
            name='acronimo',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='asistenciacabecera',
            name='descripcion',
            field=models.CharField(max_length=700),
        ),
    ]
