# Generated by Django 4.2 on 2026-04-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistenciacabecera_acronimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadetalle',
            name='observacion',
            field=models.CharField(default='-', max_length=700),
        ),
    ]
