# Generated by Django 4.2 on 2026-05-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistenciadetalle_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadetalle',
            name='tipo',
            field=models.CharField(choices=[('C', 'Catequesis'), ('M', 'Misa')], default='C', max_length=1),
        ),
    ]
