# Generated by Django 4.2 on 2026-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_asistenciadetalle_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciadetalle',
            name='tipo',
        ),
        migrations.AddField(
            model_name='asistenciadetalle',
            name='catequesis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asistenciadetalle',
            name='misa',
            field=models.BooleanField(default=True),
        ),
    ]
