# Generated by Django 4.2 on 2026-06-07 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistencia', '0006_remove_asistenciadetalle_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistenciaCabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistenciacabecera')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
