# Generated by Django 4.2 on 2026-06-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_usuarioasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='asistenciaCabecera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.asistenciacabecera'),
        ),
    ]
