# Generated by Django 4.2 on 2026-06-07 05:02

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_persona_asistenciacabecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadetalle',
            name='persona',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='asistenciaCabecera', chained_model_field='asistenciaCabecera', on_delete=django.db.models.deletion.CASCADE, to='asistencia.persona'),
        ),
    ]
