# Generated by Django 4.2 on 2026-06-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_alter_asistenciadetalle_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=200),
        ),
    ]
