# Generated by Django 4.2 on 2026-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_persona_codigo_alter_persona_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadetalle',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
    ]
